### ISSUE TITLE
Parsing FEN notation with active color, castling, etc

### ISSUE THREAD

**Issue by antononcube** [vushu/fen-grammar#2]
It would be nice if the examples in the Wikipedia page are parsed: https://en.wikipedia.org/wiki/Forsyth–Edwards_Notation .

For example:

```
rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
```

**Comment by vushu** [comment]
Yes I only focused on the positions, when you or others wish for parsing the rest I will add it, I will keep this issue open.

**Comment by vushu** [comment]
@antononcube I have now added full support for parsing fen notation.
