### ISSUE TITLE
Working with square chessboards of different sizes

### ISSUE THREAD

**Issue by antononcube** [vushu/fen-grammar#8]
It would be nice if the functionalities of this package can used with square boards that have sizes different than 8x8.

```raku
use FEN::Grammar;
say FEN::Grammar.parse('8/8/8/6k1/6R1K/8/8/8') # 8x8 board works 
say FEN::Grammar.parse('5/5/5/3k1/2R1K');      # 5x5 board does not work
```

-----

Here is an example of a 5x5 board:

![](https://raw.githubusercontent.com/antononcube/Raku-Graphviz-DOT-Chessboard/refs/heads/main/docs/initial-position-5x5.svg)

**Comment by vushu** [comment]
@antononcube I made PR for making this possible I believe, not yet fully tested.
https://github.com/vushu/fen-grammar/pull/9/files.

**Comment by vushu** [comment]
it is now release https://raku.land/zef:vushu/FEN::Grammar

please try it out.

**Comment by antononcube** [comment]
Yes! I did install the new version -- I proclaimed that upgrade [here](https://www.youtube.com/watch?v=fwQrQyWC7R0&t=220s).

**Comment by vushu** [comment]
@antononcube very cool, thanks for mentioning. 😊
